// Generated by gencpp from file line_follower/dos_sensores_IR.msg
// DO NOT EDIT!


#ifndef LINE_FOLLOWER_MESSAGE_DOS_SENSORES_IR_H
#define LINE_FOLLOWER_MESSAGE_DOS_SENSORES_IR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace line_follower
{
template <class ContainerAllocator>
struct dos_sensores_IR_
{
  typedef dos_sensores_IR_<ContainerAllocator> Type;

  dos_sensores_IR_()
    : sensor_1(0)
    , sensor_2(0)  {
    }
  dos_sensores_IR_(const ContainerAllocator& _alloc)
    : sensor_1(0)
    , sensor_2(0)  {
  (void)_alloc;
    }



   typedef int8_t _sensor_1_type;
  _sensor_1_type sensor_1;

   typedef int8_t _sensor_2_type;
  _sensor_2_type sensor_2;





  typedef boost::shared_ptr< ::line_follower::dos_sensores_IR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::line_follower::dos_sensores_IR_<ContainerAllocator> const> ConstPtr;

}; // struct dos_sensores_IR_

typedef ::line_follower::dos_sensores_IR_<std::allocator<void> > dos_sensores_IR;

typedef boost::shared_ptr< ::line_follower::dos_sensores_IR > dos_sensores_IRPtr;
typedef boost::shared_ptr< ::line_follower::dos_sensores_IR const> dos_sensores_IRConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::line_follower::dos_sensores_IR_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::line_follower::dos_sensores_IR_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::line_follower::dos_sensores_IR_<ContainerAllocator1> & lhs, const ::line_follower::dos_sensores_IR_<ContainerAllocator2> & rhs)
{
  return lhs.sensor_1 == rhs.sensor_1 &&
    lhs.sensor_2 == rhs.sensor_2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::line_follower::dos_sensores_IR_<ContainerAllocator1> & lhs, const ::line_follower::dos_sensores_IR_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace line_follower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::line_follower::dos_sensores_IR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_follower::dos_sensores_IR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_follower::dos_sensores_IR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_follower::dos_sensores_IR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_follower::dos_sensores_IR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_follower::dos_sensores_IR_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::line_follower::dos_sensores_IR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e0a028753b9e2df8eddfa1f654b5f64";
  }

  static const char* value(const ::line_follower::dos_sensores_IR_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e0a028753b9e2dfULL;
  static const uint64_t static_value2 = 0x8eddfa1f654b5f64ULL;
};

template<class ContainerAllocator>
struct DataType< ::line_follower::dos_sensores_IR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "line_follower/dos_sensores_IR";
  }

  static const char* value(const ::line_follower::dos_sensores_IR_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::line_follower::dos_sensores_IR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#fieldtype1 fieldname1\n"
"#\n"
"int8 sensor_1\n"
"int8 sensor_2\n"
;
  }

  static const char* value(const ::line_follower::dos_sensores_IR_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::line_follower::dos_sensores_IR_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor_1);
      stream.next(m.sensor_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dos_sensores_IR_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::line_follower::dos_sensores_IR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::line_follower::dos_sensores_IR_<ContainerAllocator>& v)
  {
    s << indent << "sensor_1: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sensor_1);
    s << indent << "sensor_2: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sensor_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINE_FOLLOWER_MESSAGE_DOS_SENSORES_IR_H
